### ISSUE TITLE
On weekly report

### ISSUE THREAD

**Issue by li0jing** [RiikkaYang/Event-Prediction#1]
小杨@RiikkaYang ，现在看的关于创新扩散的一些研究，也要想一下能否用来做事件分析和预测。

**Comment by li0jing** [comment]
另外，也可以直接用这个功能来写周报和讨论问题等等。

**Comment by RiikkaYang** [comment]
好的老师，我最近看的关于创新扩散的研究主要是用于在市场分析这个领域对新产品和新技术需求进行预测。下周重点调研和思考能否用某一种事件表示方法与该模型结合进行事件分析和预测。
